name: jit-sdp-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - joblib
  - r-base
  - r-remotes
  - r-reshape2
  - pip
